\getenv promaly_app_password POSTGRES_APP_PASSWORD

CREATE ROLE promaly_app LOGIN PASSWORD :'promaly_app_password';
GRANT CONNECT ON DATABASE promaly TO promaly_app;
GRANT USAGE ON SCHEMA public TO promaly_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO promaly_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO promaly_app;
ALTER DEFAULT PRIVILEGES FOR ROLE promaly IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO promaly_app;
ALTER DEFAULT PRIVILEGES FOR ROLE promaly IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO promaly_app;
